### PR TITLE
[WIP] [D7] by yanniboi: Start of fields module review.

### PR DESCRIPTION
**Pull request by yanniboi**

### CODE REVIEW

**Comment by l-besenyei** [comment]
Hi.

Installing the module throws the following exeption:

> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE {gdpr_fields_field_data} ( `name` VARCHAR(255) DEFAULT NULL COMMENT 'Machine name for field.', `plugin_type` VARCHAR(128) DEFAULT NULL COMMENT 'Plugin type of the field.', `entity_type` VARCHAR(128) DEFAULT NULL COMMENT 'Entity type of field.', `entity_bundle` VARCHAR(128) DEFAULT NULL COMMENT 'Entity bundle of field.', `property_name` VARCHAR(128) DEFAULT NULL COMMENT 'Name of the property.', `settings` LONGTEXT DEFAULT NULL COMMENT 'Additional settings.', PRIMARY KEY (`name`) ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COMMENT 'Stores GDPR field data.'; Array ( ) in db_create_table() (line 2776 of /home/levi/www/d7/includes/database/database.inc).

**Comment by yanniboi** [comment]
I've made some changes to the travis testing:

 - I've put both Drupal and DrupalPractise standards in a single phpcs implementation.
 - I've marked warnings to not cause tests to fail, only errors.
 - I've excluded some test rules (Mainly to remove class name and property restrictions such as camel case naming, etc.)

If you prefer they could go in another separate merge request.

**Comment by yanniboi** [comment]
@l-besenyei have you got any questions about my test changes? Have my changes fixed the error that you were having?

**Comment by l-besenyei** [comment]
No questions about the testing changes, and Yes, the error has been solved.

**Comment by yanniboi** [comment]
Great! Thanks

**Pull request merged**
