### PR TITLE
[D7] Start of tasks module review.

### PR DESCRIPTION
**Pull request by yanniboi**
This is built on top of the fields module.

### CODE REVIEW

**Comment by l-besenyei** [comment]
Hi.

Installing the gdpr_fields module throws the following exeption:

> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE {gdpr_fields_field_data} ( `name` VARCHAR(255) DEFAULT NULL COMMENT 'Machine name for field.', `plugin_type` VARCHAR(128) DEFAULT NULL COMMENT 'Plugin type of the field.', `entity_type` VARCHAR(128) DEFAULT NULL COMMENT 'Entity type of field.', `entity_bundle` VARCHAR(128) DEFAULT NULL COMMENT 'Entity bundle of field.', `property_name` VARCHAR(128) DEFAULT NULL COMMENT 'Name of the property.', `settings` LONGTEXT DEFAULT NULL COMMENT 'Additional settings.', PRIMARY KEY (`name`) ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COMMENT 'Stores GDPR field data.'; Array ( ) in db_create_table() (line 2776 of /home/levi/www/d7/includes/database/database.inc).

**Comment by l-besenyei** [comment]
On task edit page I get the following error:

> Error: Call to undefined function ctools_export_load_object() in gdpr_task_edit_gdpr_sar_form() (line 116 of /home/levi/www/d7/sites/all/modules/contrib/gdpr/modules/gdpr_tasks/gdpr_tasks.admin.inc).

**Comment by yanniboi** [comment]
@l-besenyei  I'm not getting that error, but maybe it has to do with ctools includes. I've added an include to be on the safe side. Does that fix your error?

**Comment by l-besenyei** [comment]
Yes it fixed that. but now I get this:

> Notice: Undefined index: und in gdpr_task_edit_gdpr_sar_form() (line 123 of /home/levi/www/d7/sites/all/modules/contrib/gdpr/modules/gdpr_tasks/gdpr_tasks.admin.inc).
Warning: Invalid argument supplied for foreach() in gdpr_task_edit_gdpr_sar_form() (line 123 of /home/levi/www/d7/sites/all/modules/contrib/gdpr/modules/gdpr_tasks/gdpr_tasks.admin.inc).

The `$task->gdpr_tasks_sar_export_parts` is empty.

User email and name is set to be included.

**Comment by l-besenyei** [comment]
For removal request, after pressing the Remove and Anonimyse Data button I get this error:

> Error: Call to undefined function gdpr_dump_get_gdpr_sanitizer() in Anonymizer->anonymize() (line 177 of /home/levi/www/d7/sites/all/modules/contrib/gdpr/modules/gdpr_tasks/src/Anonymizer.php).

**Comment by yanniboi** [comment]
https://github.com/brainsum/gdpr/pull/15#issuecomment-395340421

The information to be exported by a SARs request is now done on cron. Maybe we should not show requested tasks on the task list page, but for now I have made it just return some text rather than build the form. After cron run the gdpr_tasks_sar_export_parts field is not empty.

https://github.com/brainsum/gdpr/pull/15#issuecomment-395390984

Good catch, had not yet rewritten the anonymiser to work with brainsums sanitizer plugins (I started building this module before you made those so my plugins had slightly different function names).

Thanks

**Comment by yanniboi** [comment]
@l-besenyei  I've rebased this branch on top of 7.x-1.x after you merged https://github.com/brainsum/gdpr/pull/14

**Comment by l-besenyei** [comment]
When requesting a data export as a regular authenticated user, I get this message:

> Notice: Undefined index: format in gdpr_tasks_send_mail() (line 646 of /home/levi/www/d7/sites/all/modules/contrib/gdpr/modules/gdpr_tasks/gdpr_tasks.module).

The "Request requested (by staff)" email is disabled. If I enable it the error goes away.

After cron run, the .csv file is generated, but somehow, when trying to download it on task edit page, the dowloaded file is empty.

**Comment by yanniboi** [comment]
Yes the emails need some work. I think I updated them recently to all be disable on install. 

After processing a data export task, it is set to 'processed'. The cron needs to be run again to pack the zip file with the csvs. (See the queue worker for more info: https://github.com/brainsum/gdpr/pull/15/files#diff-2cd3db51c847547a2ae3818eb7ccc175)
The cron will then mark the task as complete at which point a user can download their export from their user dashboard.

**Comment by l-besenyei** [comment]
I've tested again, here are the steps:
SAR Request:
- User requests data export. Task is created with status: requested.
- Manual Cron run executed. Csv and zip files are created. Task status changes to: reviewing.
- Second Cron run does nothing.
- Nothing appears on /user/%user/gdpr/requests

Data Removal:
- User requests data removal. Task is created with status: requested
- Manual Cron run executed. Nothing happens.
- Nothing appears on /user/%user/gdpr/requests

**Comment by yanniboi** [comment]
## SAR Request:

### Create request:

selection_048

selection_049

### Run Cron

This creates the separate csv files and image assets as configured in field config.

selection_050

### Process task

Ie. Staff have reviewed export and approved data.

selection_051

selection_052

### Run cron

This puts all the csvs and assets in a zip file.

selection_054

**Comment by yanniboi** [comment]
## Data Removal:

### Create request:

selection_055


### Process task

selection_056

selection_059

selection_060

**Comment by yanniboi** [comment]
### /user/%user/gdpr/requests

Removals tasks do not display for the user (as at this point the account should be blocked/removed).
Data request downloads appear once they are 'closed' status.

selection_061

**Comment by l-besenyei** [comment]
Thank you for the update, I missed the manual Process part.

**Pull request merged**
