### PR TITLE
[D7] by yanniboi: Added gdpr_consent module.

### PR DESCRIPTION
**Pull request by yanniboi**
This merge request adds consent collection functionality to Drupal 7 GDPR.

Documentation and outstanding issues to follow.

### CODE REVIEW

**Comment by yanniboi** [comment]
We have started writing some proper documentation (contributions welcome ;) ) here:
https://freely-give.gitbook.io/gdpr/
https://github.com/FreelyGive/gdpr-docs


## Some Documentation and Screenshots:

### Adding consent agreements.
Consent agreements should contain the wording that users are consenting to. These are revisionable and we store which revision was consented to. Agreements are either implicit or explicit. Differences can be seen in rendering below.

**Implicit Agreement**
selection_040

**Explicit Agreement**
selection_041

### Adding consent fields
Consent fields can be added to any entity, however user is the simplest place. Fields reference a specific agreement.

selection_042

### Form rendering
Explicit consent renders as a checkbox for the user to complete. Implicit just shows the text that a user is agreeing to. Additional information can be JS toggled by clicking the '?'.

selection_043

selection_044

### Logging

Other than the current state of the consent which is stored in the field table, a simple audit trail is logged using message entities to track historic consent changes.

selection_045

**Comment by yanniboi** [comment]
@l-besenyei Have you had a look at this? Is there anything I can do to clear things up for you?

**Comment by l-besenyei** [comment]
Cant find the list of agreements? Is there a list for admins, and a one for each user?

**Comment by yanniboi** [comment]
'admin/config/gdpr/agreements' => Admin list of agreements.

'user/%user/gdpr/agreements' => List of agreements that a user has consented to.

**Comment by l-besenyei** [comment]
The 'user/%user/gdpr/agreements' page returns MENU_ACCESS_DENIED

**Comment by yanniboi** [comment]
Just checked gdpr_consent_collected_agreements().

Its access denied until you have consented to something.

**Comment by l-besenyei** [comment]
Do you have any uncommitted changes?
I have up-to-date code and the gdpr_consent_collected_agreements function fetches the consents, loads them (but does not store them in a variable), and returns MENU_ACCESS_DENIED.

**Comment by yanniboi** [comment]
Ah yes, you are right. There is a `@todo` in the function documentation that says 'Finish this'. Quite vague, but it appears that the user display still needs more work. Do you need this completed before merging? That could quite easily be done as a follow-up.

**Pull request merged**
